services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    container_name: gestion-back
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db # This service depends on postgres. Start that first.
    command: ["./wait-for-postgres.sh", "db", "python", "app.py"]
    volumes:
      - images-data:/var/lib/images/data
    environment:
      - file.upload-dir=/var/lib/images/data
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - proxy-network
      - backend

  # Database Service (Postgresql)
  db:
    container_name: gestion-back-db
    image: postgres:9.5.19-alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    

# Volumes
volumes:
  db-data:
  images-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
