package com.empresa.consumo.masivo.gestion.DTO;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import javax.validation.Valid;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * ProductoMaterial generated by hbm2java
 */
public class AddProductoMaterialDTO implements java.io.Serializable {

	
	@NotNull
	@Min(value = 1)
	private Long materialId;
	@NotNull
	@Min(value = 1)
	private Long productoId;
	@NotNull
	@Valid
	private TipoUnidadDTO tipoUnidad;
	@NotNull
	@Min(value = 0)
	private Double cantidad;

	public AddProductoMaterialDTO() {
	}

	public Long getMaterialId() {
		return materialId;
	}

	public void setMaterialId(Long materialId) {
		this.materialId = materialId;
	}

	public Long getProductoId() {
		return productoId;
	}

	public void setProductoId(Long productoId) {
		this.productoId = productoId;
	}

	public TipoUnidadDTO getTipoUnidad() {
		return tipoUnidad;
	}

	public void setTipoUnidad(TipoUnidadDTO tipoUnidad) {
		this.tipoUnidad = tipoUnidad;
	}

	public Double getCantidad() {
		return cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	
	

	
}
