package com.empresa.consumo.masivo.gestion.DTO;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * ProductoMaterial generated by hbm2java
 */
public class ModifyProductoMaterialDTO implements java.io.Serializable {

	@NotNull
	@Min(value = 1)
	private Long productoMaterialId;
	@NotNull
	private TipoUnidadDTO tipoUnidad;
	@NotNull
	@Min(value = 0)
	private Double cantidad;

	public ModifyProductoMaterialDTO() {
	}

	

	public Long getProductoMaterialId() {
		return productoMaterialId;
	}



	public void setProductoMaterialId(Long productoMaterialId) {
		this.productoMaterialId = productoMaterialId;
	}



	public TipoUnidadDTO getTipoUnidad() {
		return tipoUnidad;
	}

	public void setTipoUnidad(TipoUnidadDTO tipoUnidad) {
		this.tipoUnidad = tipoUnidad;
	}

	public Double getCantidad() {
		return cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	
	

	
}
