package com.empresa.consumo.masivo.gestion.DTO;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

/**
 * ProductoMaterial generated by hbm2java
 */
public class ProductoMaterialDTO implements java.io.Serializable {

	
	private Long productoMaterialId;
	private MaterialDTO material;
	private TipoUnidadDTO tipoUnidad;
	private Double cantidad;

	public ProductoMaterialDTO() {
	}

	

	public Long getProductoMaterialId() {
		return productoMaterialId;
	}



	public void setProductoMaterialId(Long productoMaterialId) {
		this.productoMaterialId = productoMaterialId;
	}



	public MaterialDTO getMaterial() {
		return material;
	}

	public void setMaterial(MaterialDTO material) {
		this.material = material;
	} 

	public TipoUnidadDTO getTipoUnidad() {
		return tipoUnidad;
	}

	public void setTipoUnidad(TipoUnidadDTO tipoUnidad) {
		this.tipoUnidad = tipoUnidad;
	}

	public Double getCantidad() {
		return cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	
}
