package com.empresa.consumo.masivo.gestion.DTO;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

/**
 * TipoMaterial generated by hbm2java
 */
public class TipoMaterialDTO implements java.io.Serializable {

	
	private Long tipoMaterialId;
	private String tipo;

	public TipoMaterialDTO() {
	}
	
	

	public TipoMaterialDTO(Long tipoMaterialId) {
		super();
		this.tipoMaterialId = tipoMaterialId;
	}



	public Long getTipoMaterialId() {
		return tipoMaterialId;
	}

	public void setTipoMaterialId(Long tipoMaterialId) {
		this.tipoMaterialId = tipoMaterialId;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	
}
