package com.empresa.consumo.masivo.gestion.DTO;

import lombok.Getter;
import lombok.Setter;

// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

/**
 * TipoMaterial generated by hbm2java
 */
@Getter
@Setter
public class TipoMaterialDTO implements java.io.Serializable {

	
	private Long tipoMaterialId;
	private String tipo;

	public TipoMaterialDTO() {
	}
	
	

	public TipoMaterialDTO(Long tipoMaterialId) {
		super();
		this.tipoMaterialId = tipoMaterialId;
	}

	
}
