package com.empresa.consumo.masivo.gestion.data.entity;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */

@Entity
@Table(name = "empresa", schema = "gestion")
public class Empresa implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "empresa_id", unique = true, nullable = false)
	private Long empresaId;
	@Column(name = "nombre", nullable = false)
	private String nombre;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	private Set<TipoMaterial> tipoMaterials = new HashSet<>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	private Set<Producto> productos = new HashSet<>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	private Set<Usuario> usuarios = new HashSet<>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	private Set<Material> materials = new HashSet<>(0);

	public Empresa() {
	}
	
	

	public Empresa(Long empresaId) {
		super();
		this.empresaId = empresaId;
	}
	
	



	public Empresa(String nombre) {
		super();
		this.nombre = nombre;
	}



	public Empresa(Long empresaId, String nombre) {
		this.empresaId = empresaId;
		this.nombre = nombre;
	}

	public Empresa(Long empresaId, String nombre, Set tipoMaterials, Set productos, Set usuarios, Set materials) {
		this.empresaId = empresaId;
		this.nombre = nombre;
		this.tipoMaterials = tipoMaterials;
		this.productos = productos;
		this.usuarios = usuarios;
		this.materials = materials;
	}

	public Long getEmpresaId() {
		return empresaId;
	}

	public void setEmpresaId(Long empresaId) {
		this.empresaId = empresaId;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<TipoMaterial> getTipoMaterials() {
		return tipoMaterials;
	}

	public void setTipoMaterials(Set<TipoMaterial> tipoMaterials) {
		this.tipoMaterials = tipoMaterials;
	}

	public Set<Producto> getProductos() {
		return productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

	public Set<Usuario> getUsuarios() {
		return usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public Set<Material> getMaterials() {
		return materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

	
	

}
