package com.empresa.consumo.masivo.gestion.data.entity;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material", schema = "gestion")
@Getter
@Setter
public class Material implements java.io.Serializable {

	@Id
	@SequenceGenerator(name="pk_sequence_material",sequenceName="gestion.material_id_sequence", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="pk_sequence_material")
	@Column(name = "material_id", nullable = false)
	private Long materialId;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empresa_id", nullable = false)
	private Empresa empresa;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_unidad_id", nullable = false)
	private TipoUnidad tipoUnidad;
	@Column(name = "nombre", nullable = false)
	private String nombre;
	@Column(name = "costo", nullable = false)
	private Double costo;
	@Column(name = "cantidad_compra", nullable = false)
	private Double cantidadCompra;
	@Column(name = "activo", nullable = false)
	private Boolean activo;
	@Column(name = "fecha_creacion", nullable = false)
	private LocalDateTime fechaCreacion;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
	private Set<ProductoMaterial> productoMaterials = new HashSet<>(0);

	public Material() {
	}

	public Material(Long materialId) {
		super();
		this.materialId = materialId;
	}

	public Material(Empresa empresa, TipoUnidad tipoUnidad, String nombre, Double costo,
			double cantidadCompra, Set<ProductoMaterial> productoMaterials) {
		super();
		this.empresa = empresa;
		this.tipoUnidad = tipoUnidad;
		this.nombre = nombre;
		this.costo = costo;
		this.cantidadCompra = cantidadCompra;
		this.productoMaterials = productoMaterials;
	}

	public Material(Long materialId, Empresa empresa, TipoUnidad tipoUnidad, String nombre,
			Double costo, Double cantidadCompra) {
		this.materialId = materialId;
		this.empresa = empresa;
		this.tipoUnidad = tipoUnidad;
		this.nombre = nombre;
		this.costo = costo;
		this.cantidadCompra = cantidadCompra;
	}

	public Material(Long materialId, Empresa empresa, TipoUnidad tipoUnidad, String nombre,
			Double costo, Double cantidadCompra, Set productoMaterials) {
		this.materialId = materialId;
		this.empresa = empresa;
		this.tipoUnidad = tipoUnidad;
		this.nombre = nombre;
		this.costo = costo;
		this.cantidadCompra = cantidadCompra;
		this.productoMaterials = productoMaterials;
	}
}
