package com.empresa.consumo.masivo.gestion.data.entity;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material", schema = "gestion")
public class Material implements java.io.Serializable {

	@Id
	@SequenceGenerator(name="pk_sequence_material",sequenceName="gestion.material_id_sequence", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="pk_sequence_material")
	@Column(name = "material_id", nullable = false)
	private Long materialId;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empresa_id", nullable = false)
	private Empresa empresa;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_material_id", nullable = false)
	private TipoMaterial tipoMaterial;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_unidad_id", nullable = false)
	private TipoUnidad tipoUnidad;
	@Column(name = "nombre", nullable = false)
	private String nombre;
	@Column(name = "costo", nullable = false)
	private Double costo;
	@Column(name = "cantidad_compra", nullable = false)
	private Double cantidadCompra;
	@Column(name = "activo", nullable = false)
	private Boolean activo;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
	private Set<ProductoMaterial> productoMaterials = new HashSet<>(0);

	public Material() {
	}
	
	

	public Material(Long materialId) {
		super();
		this.materialId = materialId;
	}



	public Material(Empresa empresa, TipoMaterial tipoMaterial, TipoUnidad tipoUnidad, String nombre, Double costo,
			double cantidadCompra, Set<ProductoMaterial> productoMaterials) {
		super();
		this.empresa = empresa;
		this.tipoMaterial = tipoMaterial;
		this.tipoUnidad = tipoUnidad;
		this.nombre = nombre;
		this.costo = costo;
		this.cantidadCompra = cantidadCompra;
		this.productoMaterials = productoMaterials;
	}



	public Material(Long materialId, Empresa empresa, TipoMaterial tipoMaterial, TipoUnidad tipoUnidad, String nombre,
			Double costo, Double cantidadCompra) {
		this.materialId = materialId;
		this.empresa = empresa;
		this.tipoMaterial = tipoMaterial;
		this.tipoUnidad = tipoUnidad;
		this.nombre = nombre;
		this.costo = costo;
		this.cantidadCompra = cantidadCompra;
	}

	public Material(Long materialId, Empresa empresa, TipoMaterial tipoMaterial, TipoUnidad tipoUnidad, String nombre,
			Double costo, Double cantidadCompra, Set productoMaterials) {
		this.materialId = materialId;
		this.empresa = empresa;
		this.tipoMaterial = tipoMaterial;
		this.tipoUnidad = tipoUnidad;
		this.nombre = nombre;
		this.costo = costo;
		this.cantidadCompra = cantidadCompra;
		this.productoMaterials = productoMaterials;
	}

	public Long getMaterialId() {
		return materialId;
	}

	public void setMaterialId(Long materialId) {
		this.materialId = materialId;
	}

	public Empresa getEmpresa() {
		return empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public TipoMaterial getTipoMaterial() {
		return tipoMaterial;
	}

	public void setTipoMaterial(TipoMaterial tipoMaterial) {
		this.tipoMaterial = tipoMaterial;
	}

	public TipoUnidad getTipoUnidad() {
		return tipoUnidad;
	}

	public void setTipoUnidad(TipoUnidad tipoUnidad) {
		this.tipoUnidad = tipoUnidad;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Double getCosto() {
		return costo;
	}

	public void setCosto(Double costo) {
		this.costo = costo;
	}

	public double getCantidadCompra() {
		return cantidadCompra;
	}

	public void setCantidadCompra(double cantidadCompra) {
		this.cantidadCompra = cantidadCompra;
	}

	public Set<ProductoMaterial> getProductoMaterials() {
		return productoMaterials;
	}

	public void setProductoMaterials(Set<ProductoMaterial> productoMaterials) {
		this.productoMaterials = productoMaterials;
	}



	public Boolean getActivo() {
		return activo;
	}



	public void setActivo(Boolean activo) {
		this.activo = activo;
	}



	public void setCantidadCompra(Double cantidadCompra) {
		this.cantidadCompra = cantidadCompra;
	}

	
}
