package com.empresa.consumo.masivo.gestion.data.entity;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", schema = "gestion")
public class Producto implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "producto_id", nullable = false)
	private Long productoId;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empresa_id", nullable = false)
	private Empresa empresa;
	@Column(name = "nombre", nullable = false)
	private String nombre;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	private Set<ProductoMaterial> productoMaterials = new HashSet<>(0);

	public Producto() {
	}

	public Producto(Long productoId, Empresa empresa, String nombre) {
		this.productoId = productoId;
		this.empresa = empresa;
		this.nombre = nombre;
	}

	public Producto(Long productoId, Empresa empresa, String nombre, Set productoMaterials) {
		this.productoId = productoId;
		this.empresa = empresa;
		this.nombre = nombre;
		this.productoMaterials = productoMaterials;
	}

	public Long getProductoId() {
		return productoId;
	}

	public void setProductoId(Long productoId) {
		this.productoId = productoId;
	}

	public Empresa getEmpresa() {
		return empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<ProductoMaterial> getProductoMaterials() {
		return productoMaterials;
	}

	public void setProductoMaterials(Set<ProductoMaterial> productoMaterials) {
		this.productoMaterials = productoMaterials;
	}

	
}
