package com.empresa.consumo.masivo.gestion.data.entity;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ProductoMaterial generated by hbm2java
 */
@Entity
@Table(name = "producto_material", schema = "gestion")
public class ProductoMaterial implements java.io.Serializable {

	@Id
	@SequenceGenerator(name="pk_sequence_producto_material",sequenceName="gestion.producto_material_id_sequence", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="pk_sequence_producto_material")
	
	@Column(name = "producto_material_id", nullable = false)
	private Long productoMaterialId;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "material_id", nullable = false)
	private Material material;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "producto_id", nullable = false)
	private Producto producto;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_unidad_id", nullable = false)
	private TipoUnidad tipoUnidad;
	@Column(name = "cantidad", nullable = false)
	private Double cantidad;

	public ProductoMaterial() {
	}

	public ProductoMaterial(Long productoMaterialId, Material material, Producto producto, TipoUnidad tipoUnidad,
			double cantidad) {
		this.productoMaterialId = productoMaterialId;
		this.material = material;
		this.producto = producto;
		this.tipoUnidad = tipoUnidad;
		this.cantidad = cantidad;
	}
	
	

	public ProductoMaterial(Material material, Producto producto, TipoUnidad tipoUnidad, double cantidad) {
		super();
		this.material = material;
		this.producto = producto;
		this.tipoUnidad = tipoUnidad;
		this.cantidad = cantidad;
	}

	public Long getProductoMaterialId() {
		return productoMaterialId;
	}

	public void setProductoMaterialId(Long productoMaterialId) {
		this.productoMaterialId = productoMaterialId;
	}

	public Material getMaterial() {
		return material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	public Producto getProducto() {
		return producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public TipoUnidad getTipoUnidad() {
		return tipoUnidad;
	}

	public void setTipoUnidad(TipoUnidad tipoUnidad) {
		this.tipoUnidad = tipoUnidad;
	}

	public Double getCantidad() {
		return cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	
}
