package com.empresa.consumo.masivo.gestion.data.entity;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * TipoMaterial generated by hbm2java
 */
@Entity
@Table(name = "tipo_material", schema = "gestion")
@Getter
@Setter
public class TipoMaterial implements java.io.Serializable {

	@Id
	@SequenceGenerator(name="pk_sequence_tipo_material",sequenceName="gestion.tipo_material_id_sequence", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="pk_sequence_tipo_material")
	@Column(name = "tipo_material_id", nullable = false)
	private Long tipoMaterialId;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empresa_id", nullable = false)
	private Empresa empresa;
	@Column(name = "tipo", nullable = false)
	private String tipo;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMaterial")
	private Set<Material> materials = new HashSet<>(0);

	public TipoMaterial() {
	}

	public TipoMaterial(Long tipoMaterialId, Empresa empresa, String tipo) {
		this.tipoMaterialId = tipoMaterialId;
		this.empresa = empresa;
		this.tipo = tipo;
	}

	public TipoMaterial(Long tipoMaterialId, Empresa empresa, String tipo, Set materials) {
		this.tipoMaterialId = tipoMaterialId;
		this.empresa = empresa;
		this.tipo = tipo;
		this.materials = materials;
	}

	
}
