package com.empresa.consumo.masivo.gestion.data.entity;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoUnidad generated by hbm2java
 */
@Entity
@Table(name = "tipo_unidad", schema = "gestion")
public class TipoUnidad implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "tipo_unidad_id", nullable = false)
	private int tipoUnidadId;
	@Column(name = "tipo", nullable = false)
	private String tipo;
	@Column(name = "unidad", nullable = false)
	private String unidad;
	@Column(name = "referecia_en_gramos", nullable = false)
	private double referenciaEnGramos;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUnidad")
	private Set<Material> materials = new HashSet<>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUnidad")
	private Set<ProductoMaterial> productoMaterials = new HashSet<>(0);

	public TipoUnidad() {
	}

	public TipoUnidad(int tipoUnidadId, String tipo, String unidad, double referenciaEnGramos) {
		this.tipoUnidadId = tipoUnidadId;
		this.tipo = tipo;
		this.unidad = unidad;
		this.referenciaEnGramos = referenciaEnGramos;
	}

	public TipoUnidad(int tipoUnidadId, String tipo, String unidad, double referenciaEnGramos, Set materials,
			Set productoMaterials) {
		this.tipoUnidadId = tipoUnidadId;
		this.tipo = tipo;
		this.unidad = unidad;
		this.referenciaEnGramos = referenciaEnGramos;
		this.materials = materials;
		this.productoMaterials = productoMaterials;
	}

	public int getTipoUnidadId() {
		return tipoUnidadId;
	}

	public void setTipoUnidadId(int tipoUnidadId) {
		this.tipoUnidadId = tipoUnidadId;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getUnidad() {
		return unidad;
	}

	public void setUnidad(String unidad) {
		this.unidad = unidad;
	}

	public double getReferenciaEnGramos() {
		return referenciaEnGramos;
	}

	public void setReferenciaEnGramos(double referenciaEnGramos) {
		this.referenciaEnGramos = referenciaEnGramos;
	}

	public Set<Material> getMaterials() {
		return materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

	public Set<ProductoMaterial> getProductoMaterials() {
		return productoMaterials;
	}

	public void setProductoMaterials(Set<ProductoMaterial> productoMaterials) {
		this.productoMaterials = productoMaterials;
	}

	

}
