package com.empresa.consumo.masivo.gestion.data.entity;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMaterial generated by hbm2java
 */
@Entity
@Table(name = "tipo_material", schema = "gestion")
public class TipoMaterial implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "tipo_material_id", nullable = false)
	private int tipoMaterialId;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empresa_id", nullable = false)
	private Empresa empresa;
	@Column(name = "tipo", nullable = false)
	private String tipo;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMaterial")
	private Set<Material> materials = new HashSet<>(0);

	public TipoMaterial() {
	}

	public TipoMaterial(int tipoMaterialId, Empresa empresa, String tipo) {
		this.tipoMaterialId = tipoMaterialId;
		this.empresa = empresa;
		this.tipo = tipo;
	}

	public TipoMaterial(int tipoMaterialId, Empresa empresa, String tipo, Set materials) {
		this.tipoMaterialId = tipoMaterialId;
		this.empresa = empresa;
		this.tipo = tipo;
		this.materials = materials;
	}

	public int getTipoMaterialId() {
		return tipoMaterialId;
	}

	public void setTipoMaterialId(int tipoMaterialId) {
		this.tipoMaterialId = tipoMaterialId;
	}

	public Empresa getEmpresa() {
		return empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set<Material> getMaterials() {
		return materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

	
}
