package com.empresa.consumo.masivo.gestion.data.entity;
// Generated 28/12/2018 07:26:27 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * TipoUnidad generated by hbm2java
 */
@Entity
@Table(name = "tipo_unidad", schema = "gestion")
@Getter
@Setter 
public class TipoUnidad implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "tipo_unidad_id", nullable = false)
	private Long tipoUnidadId;
	@Column(name = "tipo", nullable = false)
	private String tipo;
	@Column(name = "unidad", nullable = false)
	private String unidad;
	@Column(name = "referencia_en_gramos", nullable = false)
	private Double referenciaEnGramos;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUnidad")
	private Set<Material> materials = new HashSet<>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUnidad")
	private Set<ProductoMaterial> productoMaterials = new HashSet<>(0);

	public TipoUnidad() {
	}

	public TipoUnidad(Long tipoUnidadId, String tipo, String unidad, double referenciaEnGramos) {
		this.tipoUnidadId = tipoUnidadId;
		this.tipo = tipo;
		this.unidad = unidad;
		this.referenciaEnGramos = referenciaEnGramos;
	}

	public TipoUnidad(Long tipoUnidadId, String tipo, String unidad, double referenciaEnGramos, Set materials,
			Set productoMaterials) {
		this.tipoUnidadId = tipoUnidadId;
		this.tipo = tipo;
		this.unidad = unidad;
		this.referenciaEnGramos = referenciaEnGramos;
		this.materials = materials;
		this.productoMaterials = productoMaterials;
	}	

}
